<?php
error_reporting(0);
session_start();

/*
 * Author: KEANT Technologies              Date: 18 MAY 2026
 *
 * Purpose:
 * This logic handles account number retrieval for Account Detail navigation
 * using URL request parameters instead of shared PHP SESSION storage.
 *
 * Previous Behavior:
 * - Account number fetched from PHP SESSION
 * - Shared session caused account overwrite across multiple browser tabs
 *
 * New Behavior:
 * - Account number fetched from URL parameter ($_GET['acc'])
 * - Base64 decoded before processing
 * - Supports independent multi-tab account navigation
 *
 * Key Changes:
 * - Removed dependency on $_SESSION['accNo']
 * - Added URL parameter-based account handling
 * - Preserved existing account trimming/format logic
 *
 * Change Tag:
 * ----------------------------------------------------------------------------
 * AH18052026 | Replaced session-based account handling with URL parameter
 * ----------------------------------------------------------------------------
 * ============================================================================
 */


if(!isset($_SESSION['email']))
{
  header('Location: logout.php');
  exit();
  }
include('config.php');
//print_r($_SESSION);exit;
// $accountNo =$_GET['accNo'];
//$accountNo =base64_decode($_GET['accNo']);


//AH18052026 : Starts
// $accountNo =base64_decode($_SESSION['accNo']);
$accountNo = '';
if(isset($_GET['acc']) && $_GET['acc'] != '')
{
    $accountNo = base64_decode($_GET['acc']);
}
// $acc=str_replace("a","#",$accountNo );
$acc = trim($accountNo);
//AH18052026 End 

$query="SELECT FULL_NAME ,ACCOUNT_NUMBER , Notes_History,Status_Date,Last_Activity_Date,RMSFILENUM FROM SEARCH_QUERY_DATA where ACCOUNT_NUMBER='".$acc."'";

$result = mysqli_query($conn,$query);
$row=mysqli_fetch_assoc($result);
$RMSFILENUM=$row['RMSFILENUM'];
/*$querycombined="WITH CTE AS

(

SELECT A.*, LEFT(A.HSTTRANCDE,2) AS HSTTRCODE, LEFT(A.RMSFLDCODE,1) AS FIELDCD1, SUBSTRING(A.RMSFLDCODE,2,2) AS FIELDCD2,

CONCAT(LEFT(A.RMSFLDCODE,1),'',RIGHT(A.RMSFLDCODE,3)) AS FIELDCD3, RIGHT(A.RMSFLDCODE,3) AS FIELDCD4, LEFT(UCASE(A.HSTTRANDSC),3) AS OLDSTATUS,

SUBSTRING(UCASE(A.HSTTRANDSC),21,3) AS NEWSTATUS, CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',RIGHT(UCASE(A.HSTTRANDSC),2)) AS STATUSBAL,

SUBSTRING(UCASE(A.HSTTRANDSC),6,4) AS ASSIGNFIRM, FORMAT(CONCAT(SUBSTRING(UCASE(HSTTRANDSC),11,11),'.',RIGHT(UCASE(HSTTRANDSC),2))*1,2) AS ASSIGNBAL,

CONCAT(LEFT(UCASE(A.HSTTRANDSC),11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),12,2)) AS BALOLD,

CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),32,2)) AS BALNEW,

LEFT(UCASE(A.HSTTRANDSC),2) AS TWOOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,2) AS TWONEW,

CONCAT(LEFT(UCASE(A.HSTTRANDSC),11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),12,2)) AS JINTRTOLD,

CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),31,2)) AS JINTRTNEW,

CONCAT(LEFT(UCASE(A.HSTTRANDSC),2),'.',SUBSTRING(UCASE(A.HSTTRANDSC),3,2)) AS COMMRTOLD,

CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),6,2),'.',SUBSTRING(UCASE(A.HSTTRANDSC),8,2)) AS COMMRTNEW,

CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),11,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),22,2)) AS COMMRTBAL,

LEFT(UCASE(A.HSTTRANDSC),8) AS DATEOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,8) AS DATENEW,

LEFT(UCASE(A.HSTTRANDSC),15) AS LOCOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,15) AS LOCNEW, LEFT(UCASE(A.HSTTRANDSC),4) AS FOUROLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,4) AS FOURNEW,

LEFT(UCASE(A.HSTTRANDSC),6) AS SIXOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,6) AS SIXNEW, LEFT(UCASE(A.HSTTRANDSC),1) AS ONEOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,1) AS ONENEW,

LEFT(UCASE(A.HSTTRANDSC),20) AS TWENTYOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,20) AS TWENTYNEW, LEFT(UCASE(A.HSTTRANDSC),11) AS DESCCHECK,

(CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)

      WHEN RIGHT(A.RMSFLDCODE,3) <> 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' ELSE LEFT(A.HSTTRANCDE,2) END) AS ENTRYCODE,

(CASE WHEN (LEFT(A.HSTTRANCDE,2) >= '9' AND LEFT(A.HSTTRANCDE,2) <= '99') OR (LEFT(A.HSTTRANCDE,2) >= 'A' AND LEFT(A.HSTTRANCDE,2) <= 'ZZ' AND

LEFT(A.HSTTRANCDE,2) <> 'M1' AND LEFT(A.HSTTRANCDE,2) <> 'M2' AND LEFT(A.HSTTRANCDE,2) <> 'MR') THEN 'H' ELSE 'M' END) AS ENTRYTYPE,

(CASE WHEN

((CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)

      WHEN RIGHT(A.RMSFLDCODE,3) <> 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' ELSE LEFT(A.HSTTRANCDE,2) END) = '90'

      AND CAST(A.RMSTRANDTE AS DATE) <= B.AACA_RCVD_DT) THEN 'PP' ELSE

(CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)

      WHEN RIGHT(A.RMSFLDCODE,3) <> 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' ELSE LEFT(A.HSTTRANCDE,2) END) END) AS PRE_NOTES 

FROM RMSPHISTFL A

LEFT JOIN MASTER_DATA_DB B ON A.RMSFILENUM = B.RMSFILENUM

WHERE A.RMSFILENUM IN (SELECT RMSFILENUM FROM SEARCH_QUERY_DATA WHERE ACCOUNT_NUMBER = '".$acc."')

)

SELECT CAST(A.RMSTRANDTE AS DATE) AS 'Date of Entry', A.PRE_NOTES AS 'Code',

(CASE WHEN A.HSTTRCODE = 'LR' THEN 'AACA PROCESSED PAYMENT'

      WHEN A.PRE_NOTES = 'PP' THEN 'PRE-PLACEMENT NOTES'

      WHEN A.HSTTRCODE = '9L' THEN B.SYSDESC

      WHEN A.HSTTRCODE = '9Z' THEN B.SYSDESC

      WHEN A.HSTTRCODE = '9O' THEN B.SYSDESC

      WHEN A.HSTTRCODE = '9W' THEN B.SYSDESC

      WHEN A.HSTTRCODE = '9J' THEN B.SYSDESC

     WHEN A.HSTTRCODE = '95' AND A.DESCCHECK = 'OLD OFFICER' THEN 'PORTFOLIO CODE CHANGE'

      WHEN A.ENTRYTYPE = 'H' THEN B.SYSDESC

      WHEN A.FIELDCD3 = 'CAD1' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' ADDRESS 1')

      WHEN A.FIELDCD3 = 'CAD2' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' ADDRESS 2')

      WHEN A.FIELDCD3 = 'CAD3' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' ADDRESS 3')

      WHEN A.FIELDCD3 = 'CBDY' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' BIRTHDAY')

                 WHEN A.FIELDCD3 = 'CCNT' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' COUNTY')

      WHEN A.FIELDCD3 = 'CCTY' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' CITY')

      WHEN A.FIELDCD3 = 'CHPH' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' HOME PHONE')

      WHEN A.FIELDCD3 = 'COPH' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' OFFICE PHONE')

      WHEN A.FIELDCD3 = 'CSTC' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' STATE')

      WHEN A.FIELDCD3 = 'CSDT' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' SUIT FILED DATE')

      WHEN A.FIELDCD3 = 'CTYP' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' CUSTOMER TYPE')

      WHEN A.FIELDCD3 = 'CZIP' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' ZIP')

      WHEN A.FIELDCD3 = 'CTAX' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' SSN')

      WHEN A.FIELDCD3 = 'AAD1' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' ADDRESS 1')

      WHEN A.FIELDCD3 = 'AAD2' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' ADDRESS 2')

      WHEN A.FIELDCD3 = 'ACTY' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' CITY')

      WHEN A.FIELDCD3 = 'ANAM' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' NAME')

      WHEN A.FIELDCD3 = 'AOPH' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' PHONE')

      WHEN A.FIELDCD3 = 'ASTC' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' STATE')

      WHEN A.FIELDCD3 = 'AZIP' THEN CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' AZIP')

      WHEN A.FIELDCD3 = 'EAD1' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ADDRESS 1')

      WHEN A.FIELDCD3 = 'EAD2' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ADDRESS 2')

      WHEN A.FIELDCD3 = 'ECNT' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' COUNTY')

      WHEN A.FIELDCD3 = 'ECTY' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' CITY')

      WHEN A.FIELDCD3 = 'ENNM' THEN CONCAT('EMPLOYER ',A.FIELDCD2,' NAME')

      WHEN A.FIELDCD3 = 'EOPH' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' OFFICE PHONE')

      WHEN A.FIELDCD3 = 'ESTC' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' STATE')

      WHEN A.FIELDCD3 = 'EZIP' THEN CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ZIP')

      WHEN A.FIELDCD3 = 'MAD1' AND A.RMSFLDCODE <> 'MASAD1' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,' ADDRESS 1')

      WHEN A.FIELDCD3 = 'MAD2' AND A.RMSFLDCODE <> 'MASAD2' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,' ADDRESS 2')

      WHEN A.FIELDCD3 = 'MBKC' AND A.RMSFLDCODE <> 'MASBKC' THEN CONCAT('CODEBTOR ',A.FIELDCD2,' BANKRUPTCY CHAPTER')

      WHEN A.FIELDCD3 = 'MCNT' AND A.RMSFLDCODE <> 'MASCNT' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,' COUNTY')

      WHEN A.FIELDCD3 = 'MHPH' AND A.RMSFLDCODE <> 'MASHPH' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,'  HOME PHONE')

      WHEN A.FIELDCD3 = 'MOPH' AND A.RMSFLDCODE <> 'MASHPH' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,'  OFFICE PHONE')

      WHEN A.FIELDCD3 = 'MSTC' AND A.RMSFLDCODE <> 'MASSTC' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,'  STATE')

      WHEN A.FIELDCD3 = 'MZIP' AND A.RMSFLDCODE <> 'MASZIP' THEN CONCAT('FULL DEBTOR ',A.FIELDCD2,' ZIP')

      WHEN C.FIELDDESC = '' THEN A.RMSFLDCODE ELSE C.FIELDDESC END) AS 'Status/Note_Type',

(CASE WHEN A.ENTRYTYPE = 'H' THEN UCASE(A.HSTTRANDSC)

                 WHEN A.HSTTRCODE = '9L' THEN UCASE(A.HSTTRANDSC)

      WHEN A.HSTTRCODE = '9Z' THEN UCASE(A.HSTTRANDSC)

      WHEN A.HSTTRCODE = '9O' THEN UCASE(A.HSTTRANDSC)

      WHEN A.HSTTRCODE = '9W' THEN UCASE(A.HSTTRANDSC)

      WHEN A.HSTTRCODE = '9J' THEN UCASE(A.HSTTRANDSC)

      WHEN A.RMSFLDCODE = 'MASSTS' THEN CONCAT('OLD: (',A.OLDSTATUS,') ',D.SYSDESC,' | ','NEW: (',A.NEWSTATUS,') ',E.SYSDESC)

      WHEN A.FIELDCD4 = 'AD1' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'AD2' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'BDY' THEN CONCAT('OLD: ',A.DATEOLD,' | ','NEW: ',A.DATENEW)

      WHEN A.FIELDCD4 = 'CNT' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'CTY' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'ENM' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'FNM' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'LNM' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'HPH' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'OPH' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'TAX' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'TYP' THEN CONCAT('OLD: ',A.ONEOLD,' | ','NEW: ',A.ONENEW)

      WHEN A.FIELDCD4 = 'ZIP' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD4 = 'SDT' THEN CONCAT('OLD: ',A.DATEOLD,' | ','NEW: ',A.DATENEW)

      WHEN A.FIELDCD4 = 'STC' THEN CONCAT('OLD: ',A.TWOOLD,' | ','NEW: ',A.TWONEW)

      WHEN A.FIELDCD3 = 'ANAM' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD3 = 'CAD3' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.FIELDCD3 = 'ENNM' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASATT' THEN CONCAT('ASSIGNED FIRM: ',A.ASSIGNFIRM,'     |     ','ASSIGNED BALANCE: ','$', A.ASSIGNBAL)

      WHEN A.FIELDCD3 = 'MBKC' THEN CONCAT('OLD: ',A.TWOOLD,' | ',' NEW: ',A.TWONEW)

      WHEN A.RMSFLDCODE = 'MASACT' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASBCT' THEN CONCAT('OLD: ',A.TWENTYOLD,' | ',' NEW: ',A.TWENTYNEW)

      WHEN A.RMSFLDCODE = 'MASBNR' THEN CONCAT('OLD: ',A.TWENTYOLD,' | ',' NEW: ',A.TWENTYNEW)

      WHEN A.RMSFLDCODE = 'MASC7D' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASCFG' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASCDT' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASCNT' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASCOM' THEN CONCAT('OLD: ',A.COMMRTOLD,' | ',' NEW: ',A.COMMRTNEW)

      WHEN A.RMSFLDCODE = 'MASCOR' THEN CONCAT('OLD: ',A.FOUROLD,' | ',' NEW: ',A.FOURNEW)

      WHEN A.RMSFLDCODE = 'MASCSD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASDAS' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASDCO' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASDSD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASEXD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASFRD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASHPH' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASJDT' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASLCC' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASLCN' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASLCD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASLCT' THEN CONCAT('OLD: ',A.SIXOLD,' | ',' NEW: ',A.SIXNEW)

      WHEN A.RMSFLDCODE = 'MASLDT' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASLID' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASLOC' THEN CONCAT('OLD: ',A.LOCOLD,' | ',' NEW: ',A.LOCNEW)

      WHEN A.RMSFLDCODE = 'MASLPD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASMTD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASNCD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASNMD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASOFF' THEN CONCAT('OLD: ',A.SIXOLD,' | ',' NEW: ',A.SIXNEW)

      WHEN A.RMSFLDCODE = 'MASPAE' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASPAM' THEN CONCAT('OLD: ','$', FORMAT((TRIM(A.BALOLD)*1),2),' | ',' NEW: ','$', FORMAT((TRIM(A.BALNEW)*1),2))

      WHEN A.RMSFLDCODE = 'MASPCD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASPDD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASPCN' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASPFD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASRAD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASSLD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASSVD' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASTZC' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

     WHEN A.RMSFLDCODE = 'MASU01' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASU02' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASU03' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASU04' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASU13' THEN CONCAT('OLD: ',UCASE(A.HSTTRANDSC))

      WHEN A.RMSFLDCODE = 'MASU05' THEN CONCAT('OLD: ','$',FORMAT((TRIM(A.BALOLD)*1),2),' | ',' NEW: ','$',FORMAT((TRIM(A.BALNEW)*1),2))

      WHEN A.PRE_NOTES = 'MT' AND A.RMSFLDCODE = 'MASU06' THEN CONCAT('OLD: ',TRIM(A.JINTRTOLD)+0,' | ',' NEW: ',TRIM(A.JINTRTNEW)+0)

      WHEN A.PRE_NOTES = 'MT' AND A.RMSFLDCODE = 'MASU07' THEN CONCAT('OLD: ',TRIM(A.JINTRTOLD)+0,' | ',' NEW: ',TRIM(A.JINTRTNEW)+0)

      WHEN A.RMSFLDCODE = 'MASU09' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      WHEN A.RMSFLDCODE = 'MASU10' THEN CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)

      ELSE UCASE(A.HSTTRANDSC) END) AS 'Detailed_Description',

A.RMSAUDITID AS 'User'

FROM CTE A

LEFT JOIN RMSPSYSCDE B ON A.HSTTRCODE = B.SYSCODETYP

LEFT JOIN FIELDCDE_DESC C ON A.RMSFLDCODE = C.RMSFLDCODE

LEFT JOIN RMSPSYSCDE D ON A.OLDSTATUS = D.SYSCODETYP AND D.RMSRECTYPE = 2

LEFT JOIN RMSPSYSCDE E ON A.NEWSTATUS = E.SYSCODETYP AND E.RMSRECTYPE = 2

ORDER BY A.RMSTRANDTE DESC, A.RRNHSTFLBK ";*/
$querycombined=" WITH CTE1 AS

 (

 SELECT A.*, LEFT(A.HSTTRANCDE,2) AS HSTTRCODE, LEFT(A.RMSFLDCODE,1) AS FIELDCD1, SUBSTRING(A.RMSFLDCODE,2,2) AS FIELDCD2,

 CONCAT(LEFT(A.RMSFLDCODE,1),'',RIGHT(A.RMSFLDCODE,3)) AS FIELDCD3, RIGHT(A.RMSFLDCODE,3) AS FIELDCD4, LEFT(UCASE(A.HSTTRANDSC),3) AS OLDSTATUS,

 SUBSTRING(UCASE(A.HSTTRANDSC),21,3) AS NEWSTATUS, CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',RIGHT(UCASE(A.HSTTRANDSC),2)) AS STATUSBAL,

 SUBSTRING(UCASE(A.HSTTRANDSC),6,4) AS ASSIGNFIRM, FORMAT(CONCAT(SUBSTRING(UCASE(HSTTRANDSC),11,11),'.',RIGHT(UCASE(HSTTRANDSC),2))*1,2) AS ASSIGNBAL,

 CONCAT(LEFT(UCASE(A.HSTTRANDSC),11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),12,2)) AS BALOLD,

 CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),32,2)) AS BALNEW,

 LEFT(UCASE(A.HSTTRANDSC),2) AS TWOOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,2) AS TWONEW,

 CONCAT(LEFT(UCASE(A.HSTTRANDSC),11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),12,2)) AS JINTRTOLD,

 CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),21,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),31,2)) AS JINTRTNEW,

 CONCAT(LEFT(UCASE(A.HSTTRANDSC),2),'.',SUBSTRING(UCASE(A.HSTTRANDSC),3,2)) AS COMMRTOLD,

 CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),6,2),'.',SUBSTRING(UCASE(A.HSTTRANDSC),8,2)) AS COMMRTNEW,

 CONCAT(SUBSTRING(UCASE(A.HSTTRANDSC),11,11),'.',SUBSTRING(UCASE(A.HSTTRANDSC),22,2)) AS COMMRTBAL,

 LEFT(UCASE(A.HSTTRANDSC),8) AS DATEOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,8) AS DATENEW,

 LEFT(UCASE(A.HSTTRANDSC),15) AS LOCOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,15) AS LOCNEW, LEFT(UCASE(A.HSTTRANDSC),4) AS FOUROLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,4) AS FOURNEW,

 LEFT(UCASE(A.HSTTRANDSC),6) AS SIXOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,6) AS SIXNEW, LEFT(UCASE(A.HSTTRANDSC),1) AS ONEOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,1) AS ONENEW,

 LEFT(UCASE(A.HSTTRANDSC),20) AS TWENTYOLD, SUBSTRING(UCASE(A.HSTTRANDSC),21,20) AS TWENTYNEW, LEFT(UCASE(A.HSTTRANDSC),11) AS DESCCHECK,

 (CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)
 

      WHEN RIGHT(A.RMSFLDCODE,3) < 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' ELSE LEFT(A.HSTTRANCDE,2) END) AS ENTRYCODE,

 (CASE WHEN (LEFT(A.HSTTRANCDE,2) = '9' AND LEFT(A.HSTTRANCDE,2) <= '99') OR (LEFT(A.HSTTRANCDE,2) = 'A' AND LEFT(A.HSTTRANCDE,2) <= 'ZZ' AND

 LEFT(A.HSTTRANCDE,2) < 'M1' AND LEFT(A.HSTTRANCDE,2) < 'M2' AND LEFT(A.HSTTRANCDE,2) < 'MR') THEN 'H' ELSE 'M' END) AS ENTRYTYPE,

 (CASE WHEN

 ((CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)

      WHEN RIGHT(A.RMSFLDCODE,3) < 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' ELSE LEFT(A.HSTTRANCDE,2) END) = '90'

      AND CAST(A.RMSTRANDTE AS DATE) <= B.AACA_RCVD_DT) THEN 'PP' ELSE

 (CASE WHEN RIGHT(A.RMSFLDCODE,3) = 'STS' AND LEFT(A.HSTTRANCDE,2) = 'M2' THEN SUBSTRING(UCASE(A.HSTTRANDSC),21,3)

      WHEN RIGHT(A.RMSFLDCODE,3) < 'STS' AND (LEFT(A.HSTTRANCDE,2) = 'M2' OR LEFT(A.HSTTRANCDE,2) = 'M1') THEN 'MT' 
      ELSE LEFT(A.HSTTRANCDE,2) END) END) AS PRE_NOTES

 FROM RMSPHISTFL A

 LEFT JOIN MASTER_DATA_DB B ON A.RMSFILENUM = B.RMSFILENUM

 WHERE A.RMSFILENUM IN (SELECT RMSFILENUM FROM SEARCH_QUERY_DATA WHERE ACCOUNT_NUMBER = '".$acc."')

 )


 SELECT CAST(A.RMSTRANDTE AS DATE) AS 'Date of Entry',
 cast(A.PRE_NOTES AS CHAR CHARACTER SET utf8mb4)AS 'Code',

      (CASE
    WHEN A.HSTTRCODE = 'LR' THEN CAST('AACA PROCESSED PAYMENT' AS CHAR CHARACTER SET utf8mb4)
    WHEN A.PRE_NOTES = 'PP' THEN CAST('PRE-PLACEMENT NOTES' AS CHAR CHARACTER SET utf8mb4)
    WHEN A.HSTTRCODE IN ('9L', '9Z', '9O', '9W', '9J') THEN CAST(B.SYSDESC AS CHAR CHARACTER SET utf8mb4)
    WHEN A.HSTTRCODE = '95' AND A.DESCCHECK = 'OLD OFFICER' THEN CAST('PORTFOLIO CODE CHANGE' AS CHAR CHARACTER SET utf8mb4)
    WHEN A.ENTRYTYPE = 'H' THEN CAST(B.SYSDESC AS CHAR CHARACTER SET utf8mb4)
    WHEN A.FIELDCD3 = 'CAD1' THEN CAST(CONCAT('CODEBTOR ', A.FIELDCD2, ' ADDRESS 1') AS CHAR CHARACTER SET utf8mb4)
    WHEN A.FIELDCD3 = 'CAD2' THEN CAST(CONCAT('CODEBTOR ', A.FIELDCD2, ' ADDRESS 2') AS CHAR CHARACTER SET utf8mb4)
    WHEN A.FIELDCD3 = 'CAD3' THEN CAST(CONCAT('CODEBTOR ', A.FIELDCD2, ' ADDRESS 3') AS CHAR CHARACTER SET utf8mb4)
    WHEN A.FIELDCD3 = 'CBDY' THEN CAST(CONCAT('CODEBTOR ', A.FIELDCD2, ' BIRTHDAY') AS CHAR CHARACTER SET utf8mb4)
     WHEN A.FIELDCD3 = 'CCNT' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' COUNTY') AS CHAR CHARACTER SET utf8mb4)
      WHEN A.FIELDCD3 = 'CCTY' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' CITY') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CHPH' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' HOME PHONE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'COPH' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' OFFICE PHONE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CSTC' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' STATE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CSDT' THEN cast(CONCAT('CODEBTOR ',A.FIELDCD2,' SUIT FILED DATE')AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CTYP' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' CUSTOMER TYPE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CZIP' THEN cast(CONCAT('CODEBTOR ',A.FIELDCD2,' ZIP') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CTAX' THEN cast(CONCAT('CODEBTOR ',A.FIELDCD2,' SSN') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'AAD1' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' ADDRESS 1') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'AAD2' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' ADDRESS 2') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ACTY' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' CITY') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ANAM' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' NAME') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'AOPH' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' PHONE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ASTC' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' STATE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'AZIP' THEN CAST(CONCAT('DEFENDANT ATTORNEY ',A.FIELDCD2,' AZIP') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'EAD1' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ADDRESS 1') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'EAD2' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ADDRESS 2') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ECNT' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' COUNTY') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ECTY' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' CITY') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ENNM' THEN CAST(CONCAT('EMPLOYER ',A.FIELDCD2,' NAME') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'EOPH' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' OFFICE PHONE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ESTC' THEN CAST(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' STATE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'EZIP' THEN cast(CONCAT('FULL EMPLOYER ',A.FIELDCD2,' ZIP') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MAD1' AND A.RMSFLDCODE < 'MASAD1' THEN CAST(CONCAT('FULL DEBTOR ',A.FIELDCD2,' ADDRESS 1') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MAD2' AND A.RMSFLDCODE < 'MASAD2' THEN CAST(CONCAT('FULL DEBTOR ',A.FIELDCD2,' ADDRESS 2') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MBKC' AND A.RMSFLDCODE < 'MASBKC' THEN CAST(CONCAT('CODEBTOR ',A.FIELDCD2,' BANKRUPTCY CHAPTER') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MCNT' AND A.RMSFLDCODE < 'MASCNT' THEN CAST(CONCAT('FULL DEBTOR ',A.FIELDCD2,' COUNTY') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MHPH' AND A.RMSFLDCODE < 'MASHPH' THEN cast(CONCAT('FULL DEBTOR ',A.FIELDCD2,'  HOME PHONE')AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MOPH' AND A.RMSFLDCODE < 'MASHPH' THEN cast(CONCAT('FULL DEBTOR ',A.FIELDCD2,'  OFFICE PHONE')AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MSTC' AND A.RMSFLDCODE < 'MASSTC' THEN CAST(CONCAT('FULL DEBTOR ',A.FIELDCD2,'  STATE') AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MZIP' AND A.RMSFLDCODE < 'MASZIP' THEN cast(CONCAT('FULL DEBTOR ',A.FIELDCD2,' ZIP')AS CHAR CHARACTER SET utf8mb4)

      WHEN C.FIELDDESC = '' THEN CAST(A.RMSFLDCODE AS CHAR CHARACTER SET utf8mb4)
    ELSE CAST(B.SYSDESC AS CHAR CHARACTER SET utf8mb4)
 END) AS 'Status/Note_Type',
 (CASE WHEN A.ENTRYTYPE = 'H' THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)

                 WHEN A.HSTTRCODE = '9L' THEN CAST(UCASE(A.HSTTRANDSC)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.HSTTRCODE = '9Z' THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.HSTTRCODE = '9O' THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.HSTTRCODE = '9W' THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.HSTTRCODE = '9J' THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)

 WHEN A.RMSFLDCODE = 'MASSTS' THEN 
CASE
WHEN A.HSTTRANDSC IS NOT NULL AND A.HSTTRANDSC <> ''
THEN CAST(UCASE(A.HSTTRANDSC) AS CHAR CHARACTER SET utf8mb4)
ELSE CAST(CONCAT('OLD: (',A.OLDSTATUS,') ',COALESCE(D.SYSDESC,''),' | ',
'NEW: (',A.NEWSTATUS,') ',COALESCE(E.SYSDESC,'')) AS CHAR CHARACTER SET utf8mb4)
END

      WHEN A.FIELDCD4 = 'AD1' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'AD2' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'BDY' THEN CAST(CONCAT('OLD: ',A.DATEOLD,' | ','NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'CNT' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'CTY' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'ENM' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'FNM' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'LNM' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'HPH' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'OPH' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'TAX' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'TYP' THEN CAST(CONCAT('OLD: ',A.ONEOLD,' | ','NEW: ',A.ONENEW) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'ZIP' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'SDT' THEN CAST(CONCAT('OLD: ',A.DATEOLD,' | ','NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD4 = 'STC' THEN CAST(CONCAT('OLD: ',A.TWOOLD,' | ','NEW: ',A.TWONEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ANAM' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'CAD3' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'ENNM' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASATT' THEN CAST(CONCAT('ASSIGNED FIRM: ',A.ASSIGNFIRM,'     |     ','ASSIGNED BALANCE: ','$', A.ASSIGNBAL) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.FIELDCD3 = 'MBKC' THEN cast(CONCAT('OLD: ',A.TWOOLD,' | ',' NEW: ',A.TWONEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASACT' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASBCT' THEN cast(CONCAT('OLD: ',A.TWENTYOLD,' | ',' NEW: ',A.TWENTYNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASBNR' THEN cast(CONCAT('OLD: ',A.TWENTYOLD,' | ',' NEW: ',A.TWENTYNEW) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASC7D' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCFG' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCDT' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCNT' THEN cast(CONCAT('OLD: ',UCASE(A.HSTTRANDSC))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCOM' THEN cast(CONCAT('OLD: ',A.COMMRTOLD,' | ',' NEW: ',A.COMMRTNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCOR' THEN cast(CONCAT('OLD: ',A.FOUROLD,' | ',' NEW: ',A.FOURNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASCSD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASDAS' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASDCO' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASDSD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASEXD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASFRD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASHPH' THEN cast(CONCAT('OLD: ',UCASE(A.HSTTRANDSC))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASJDT' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLCC' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLCN' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLCD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLCT' THEN cast(CONCAT('OLD: ',A.SIXOLD,' | ',' NEW: ',A.SIXNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLDT' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLID' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLOC' THEN cast(CONCAT('OLD: ',A.LOCOLD,' | ',' NEW: ',A.LOCNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASLPD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASMTD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASNCD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASNMD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASOFF' THEN cast(CONCAT('OLD: ',A.SIXOLD,' | ',' NEW: ',A.SIXNEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPAE' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPAM' THEN cast(CONCAT('OLD: ','$', FORMAT((TRIM(A.BALOLD)*1),2),' | ',' NEW: ','$', FORMAT((TRIM(A.BALNEW)*1),2))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPCD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPDD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPCN' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASPFD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASRAD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASSLD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASSVD' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASTZC' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

     WHEN A.RMSFLDCODE = 'MASU01' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU02' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU03' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU04' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU13' THEN CAST(CONCAT('OLD: ',UCASE(A.HSTTRANDSC)) AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU05' THEN cast(CONCAT('OLD: ','$',FORMAT((TRIM(A.BALOLD)*1),2),' | ',' NEW: ','$',FORMAT((TRIM(A.BALNEW)*1),2))AS CHAR CHARACTER SET utf8mb4)

      WHEN A.PRE_NOTES = 'MT' AND A.RMSFLDCODE = 'MASU06' THEN cast(CONCAT('OLD: ',TRIM(A.JINTRTOLD)+0,' | ',' NEW: ',TRIM(A.JINTRTNEW)+0)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.PRE_NOTES = 'MT' AND A.RMSFLDCODE = 'MASU07' THEN cast(CONCAT('OLD: ',TRIM(A.JINTRTOLD)+0,' | ',' NEW: ',TRIM(A.JINTRTNEW)+0)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU09' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      WHEN A.RMSFLDCODE = 'MASU10' THEN cast(CONCAT('OLD: ',A.DATEOLD,' | ',' NEW: ',A.DATENEW)AS CHAR CHARACTER SET utf8mb4)

      ELSE CAST(UCASE(A.HSTTRANDSC)AS CHAR CHARACTER SET utf8mb4) END) AS 'Detailed_Description',

 CAST(A.RMSAUDITID AS CHAR CHARACTER SET utf8mb4)AS 'User'

 FROM CTE1 A

 LEFT JOIN RMSPSYSCDE B ON A.HSTTRCODE = B.SYSCODETYP

 LEFT JOIN FIELDCDE_DESC C ON A.RMSFLDCODE = C.RMSFLDCODE

 LEFT JOIN RMSPSYSCDE D ON A.OLDSTATUS = D.SYSCODETYP AND D.RMSRECTYPE IN (1, 2, 3)

 LEFT JOIN RMSPSYSCDE E ON A.NEWSTATUS = E.SYSCODETYP AND E.RMSRECTYPE IN (1, 2, 3)
 UNION ALL
 SELECT
    CAST(WFTRANDT AS CHAR CHARACTER SET utf8mb4) AS 'Date of Entry',
    CAST((SELECT TRANSCDE1
          FROM RMSPHISTFL
          WHERE RMSFILENUM = '".$RMSFILENUM."' AND TRANSCDE1 NOT IN ('M1', 'M2', 'MR')LIMIT 1) AS CHAR CHARACTER SET utf8mb4) AS 'Code',

   'GENERNAL COMMENT' as 'Status/Note_Type',
    CAST(COMMENT AS CHAR CHARACTER SET utf8mb4) AS  'Detailed_Description',

    CAST(WFUSER AS CHAR CHARACTER SET utf8mb4) AS 'User'
 FROM CMNTUP
 WHERE WFACCTNUM = '".$acc."'
 ORDER BY
    STR_TO_DATE(`Date of Entry`, '%Y-%m-%d') DESC";




//echo $querycombined;exit;
$resultcombined = mysqli_query($conn,$querycombined);
//print_r($resultcombined);exit;

?>
<!DOCTYPE html>

<html>
<head>
   <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Pipeway | BI Dashboard</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=11"/>
  <meta http-equiv="X-UA-Compatible" content="IE=10"/>
  <meta http-equiv="X-UA-Compatible" content="IE=9"/>
  <meta http-equiv="X-UA-Compatible" content="IE=8"/>
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../img/fevicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../img/fevicon.ico">
  <link rel="apple-touch-icon-precomposed" href="img/fevicon.ico">
  <link rel="shortcut icon" href="img/fevicon.ico">
  <link rel="stylesheet" href="css/dataTables.min.css">
  <link rel="stylesheet" href="css/PSnnect.min.css">
  <link rel="stylesheet" href="css/PSdataTables.min.css">
  <link rel="stylesheet" href="css/PSPanel.css">
  <link rel="stylesheet" href="css/PSdaterangepicker.css">
  </head>
  <style>
thead{background-color:#28648a;color:white;}
#radiobutton{font-weight: bold;}
.dataTables_filter {
display: none;
}
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
th, td { white-space: nowrap; font-weight:bold;}
.alignment{text-align:right;}
  th, td { white-space: nowrap; }
    div.dataTables_wrapper {
        margin: 0 auto;
    }
 
    div.container {
        width: 80%;
    }
  .dt-buttons{
  margin-left: 362px;
  margin-top: -35px;
}
.dataTables_info{display:none;}
  </style>

<body>
<table id="example" class="stripe row-border order-column" style="width:90%;margin-left:64px;" border='.'>
<div class="card-header account" style="width:90%;margin-left:64px;background-color: #28648a;">
  <p id="accdetail" style="color:white;"><b>COMBINED HISTORY</b></p>
</div>
<div class="card-header account" style="width:90%;margin-left:64px;background-color: #28648ad6;height: 31px;">
  <p id="accdetail" style="color:white;"><b>
  <?php 
  $Name=str_replace('.',"",$row['FULL_NAME'] );
  echo $Name.'   '.$row['ACCOUNT_NUMBER'];?>
  </b></p>
</div>
<div class="card-header account" style="width:90%;margin-left:64px;background-color:white;height: 31px;">
  <p id="accdetail" style="color:#28648a;"><b>CURRENT STATUS & DESCRIPTION:<?php echo $row['Notes_History'].' - ';?>STATUS DATE:<?php echo DATE("Y/m/d",strtotime($row['Status_Date'])).' - ';?>STATUS RECEIVED BY AACA:<?php echo  DATE("Y/m/d",strtotime($row['Last_Activity_Date']));?></b></p>
</div>
<thead>
<tr>
<th>Date of Entry</th>
<th>Code</th>
<th>Status/Note Type</th>
<th>Detailed Description</th>
<th >User</th>
</tr>
</thead>
<tbody>
    <?php
  if(mysqli_num_rows($resultcombined)){
 while($row1=mysqli_fetch_assoc($resultcombined)){?>
<tr>
	<td><?php echo  DATE("Y-m-d",strtotime($row1['Date of Entry']));?></td>
	<td><?php echo $row1['Code'];?></td>
	<td><?php echo $row1['Status/Note_Type'];?></td>
	<td><?php echo $row1['Detailed_Description'];?></td>
	<td><?php echo $row1['User'];?></td>
</tr>
<?php } } else{
   $msg="No record found";
   echo "<p style='color:red;text-align:center'>" . $msg . "</p>";
}?>
</tbody>
</table>
</body>
 <script src="js/PSjquery.min.js"></script>
  <script src="js/PSnnect.min.js"></script>
  <script src="js/PSslimscroll.js"></script>
  <script src="js/PSnnectPanel.js"></script>

  <script src="js/autologout.js"></script>
 <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script> -->
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
</html>